[package]
name = "jupyvim"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "net", "process", "signal", "sync", "time"] }
axum = { version = "0.7", features = ["ws"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zeromq = "0.6"
clap = { version = "4.5", features = ["derive"] }
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
uuid = { version = "1.0", features = ["v4"] }
bytes = "1.0"
futures-util = "0.3"
pulldown-cmark = "0.13.4"
mimalloc = "0.1.52"
syntect = { version = "5.3.0", default-features = false, features = ["parsing", "default-syntaxes", "default-themes", "html", "regex-fancy"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

